### ISSUE TITLE
Lightdm exception at Pam authentication

### ISSUE THREAD

**Issue by jorgeventura** [canonical/lightdm#125]
Using lightdm under container, I am having this exception at authentication. It doesn't happen in a normal machine, only in container.

(gdb) bt
#0  0x00007fa74b335e1a in __memmove_sse2_unaligned_erms () at /usr/lib/libc.so.6
#1  0x000055f1ef65e477 in  ()
#2  0x000055f1ef65f6c2 in  ()
#3  0x000055f1ef65f4bb in  ()
#4  0x00007fa74b652340 in g_main_context_dispatch () at /usr/lib/libglib-2.0.so.0
#5  0x00007fa74b69ffa9 in  ()
    at /usr/lib/libglib-2.0.so.0
#6  0x00007fa74b650c03 in g_main_loop_run ()
    at /usr/lib/libglib-2.0.so.0
#7  0x000055f1ef659db4 in  ()
#8  0x00007fa74b2b4002 in __libc_start_main
    () at /usr/lib/libc.so.6
#9  0x000055f1ef65aabe in  ()
(gdb)

**Comment by jpeisach** [comment]
Does this still occur?
