### ISSUE TITLE
lightdm: run_script: child crashes with segementation fault

### ISSUE THREAD

**Issue by Lukey3332** [canonical/lightdm#242]
Hello Everyone,
I'm passing a Xephyr X11 server running on the host into a podman container via the unix socket (`/tmp/.X11-unix/X6`), see my config of lightdm inside the container below. This used to work fine with a Ubuntu 18.04 container, but today i tried it with a openSUSE Tumbleweed container and lightdm fails to execute the startup script.

As a workaround, adding a empty option `xserver-hostname=` to the config file works.

Regards,
Lukas Straub

**Backtrace**

    Thread 3.1 "lightdm" received signal SIGSEGV, Segmentation fault.
    __strlen_avx2_rtm () at ../sysdeps/x86_64/multiarch/strlen-avx2.S:74
    74      ../sysdeps/x86_64/multiarch/strlen-avx2.S: Directory not empty.
    (gdb) bt
    #0  __strlen_avx2_rtm () at ../sysdeps/x86_64/multiarch/strlen-avx2.S:74
    #1  0x00007ffff78a4819 in __add_to_environ (name=0x5555555c9fd0 "REMOTE_HOST", value=0x0, combined=combined@entry=0x0, replace=replace@entry=1) at setenv.c:131
    #2  0x00007ffff78a4a60 in __setenv (name=<optimized out>, value=<optimized out>, replace=replace@entry=1) at setenv.c:261
    #3  0x000055555556c146 in process_start (process=process@entry=0x7fffe800cba0, block=block@entry=1) at /usr/src/debug/lightdm-1.30.0-9.2.x86_64/src/process.c:247
    #4  0x000055555556c388 in run_script (seat=seat@entry=0x5555555bc880, display_server=0x5555555d17a0, script_name=script_name@entry=0x5555555cbbc0 "/usr/etc/X11/xdm/Xstartup", user=0x5555555ce360)
    at /usr/src/debug/lightdm-1.30.0-9.2.x86_64/src/seat.c:406
    #5  0x0000555555571a43 in run_session (seat=0x5555555bc880, session=0x5555555d8130) at /usr/src/debug/lightdm-1.30.0-9.2.x86_64/src/seat.c:736
    #6  0x00007ffff7d7a9a9 in ?? () from /lib64/libgobject-2.0.so.0
    #7  0x00007ffff7d93be2 in g_signal_emit_valist () from /lib64/libgobject-2.0.so.0
    #8  0x00007ffff7d9415f in g_signal_emit () from /lib64/libgobject-2.0.so.0
    #9  0x000055555556bc25 in from_child_cb (source=<optimized out>, condition=<optimized out>, data=0x5555555d8130) at /usr/src/debug/lightdm-1.30.0-9.2.x86_64/src/session.c:531
    #10 0x00007ffff7c82122 in g_main_context_dispatch () from /lib64/libglib-2.0.so.0
    #11 0x00007ffff7c824b8 in ?? () from /lib64/libglib-2.0.so.0
    #12 0x00007ffff7c827b3 in g_main_loop_run () from /lib64/libglib-2.0.so.0
    #13 0x000055555555e4dc in main (argc=<optimized out>, argv=<optimized out>) at /usr/src/debug/lightdm-1.30.0-9.2.x86_64/src/lightdm.c:998

**lightdm --version**

    lightdm 1.30.0

**/etc/lightdm/lightdm.conf**

    [LightDM]
    start-default-seat=true
    
    [Seat:seat0]
    type=xremote
    xserver-display-number=6
    autologin-user=lukas

**Comment by Lukey3332** [comment]
Ping.
